**スライスの自習問題**

必ずＰ９５～を自分で確認しながら学習を進めてください

In [3]:
# データを作成
import numpy as np
test = np.arange(1,101)
test = test.reshape(10,10)
test

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [4]:
# 例1：testの 0 列目のデータだけ取り出しなさい
a = test[:,0]
a

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [5]:
# 例2：testの 0 行目のデータだけ取り出しなさい
a = test[0,:]
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# ①：test の5行目のデータだけ取り出しなさい
a = test[5]
a

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [10]:
# ②：testの8列目のデータだけ取り出しなさい
a = test[:, 8]
a

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [11]:
# ③：testの最後の列だけをマイナスの値を使って取り出しなさい
a = test[-1]
a

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [18]:
# ④：testの0行目から3行目までの値を取り出しなさい
# (0行目、1行目、2行目、3行目の合計4行が対象)
a = test[0:4]
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [15]:
# ⑤：testの 3列目から4列目までの値を取り出しなさい
# 3列目、4列目の2列が対象
a = test[:, 3:5]
a

array([[ 4,  5],
       [14, 15],
       [24, 25],
       [34, 35],
       [44, 45],
       [54, 55],
       [64, 65],
       [74, 75],
       [84, 85],
       [94, 95]])

In [20]:
# ⑥：testの 0行目から3行目かつ、3列目から4列目までの値を取り出しなさい
a = test[0:4, 3:5]
a

array([[ 4,  5],
       [14, 15],
       [24, 25],
       [34, 35]])